cd ../src

accelerate launch --num_processes 4 --config_file accelerate_configs/4gpu_fp16.yaml run_clm_ddp.py \
--pad_to_max_length \
--wd_LN_gamma \
--with_tracking \
--report_to wandb \
--run_name test_vanilla_opt_1.3b \
--extra_tb_stats \
--seed 1000 \
--dataset_setup bookcorpus_and_wiki \
--preprocessing_num_workers 108 \
--data_cache_dir .hf_data \
--model_cache_dir .hf_cache \
--model_type opt \
--tokenizer_name facebook/opt-350m \
--max_seq_length 2048 \
--block_size 512 \
--learning_rate 0.0004 \
--lr_scheduler_type linear \
--max_train_steps 125001 \
--num_warmup_steps 2000 \
--per_device_train_batch_size 12 \
--per_device_eval_batch_size 12 \
--gradient_accumulation_steps 4 \
--max_grad_norm 1.0 \
--weight_decay 0.1 \
--checkpointing_steps 5000 \
--tb_scalar_log_interval 2000 \
--tb_hist_log_interval 8000 \
--config_path model_configs/your_model_config.yaml \
--attn_softmax vanilla \
--output_dir output/your_output_chheckpoint_folder 
